services:
  media-server:
    build: .
    container_name: live-media-server
    ports:
      - "${PORT:-8080}:8080" # HTTP & WebSocket
      - "50000-50050:50000-50050/udp" # WebRTC Media Ports
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=8080
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
    depends_on:
      - redis
      - coturn
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: live-media-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  coturn:
    image: coturn/coturn
    container_name: coturn-server
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "49152-49250:49152-49250/udp"
    env_file:
      - path: .env
        required: false
    command:
      - turnserver
      - --log-file=stdout
      - --external-ip=${PUBLIC_IP:-127.0.0.1}
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET:-turn_default_secret_999}
      - --realm=${TURN_REALM:-live.myvps.com}
      - --total-quota=100
      - --min-port=49152
      - --max-port=49250
      - -v
      - -n
      - --no-tls
      - --no-dtls
    restart: unless-stopped

volumes:
  redis-data: