services:
  caddy:
    image: caddy:alpine
    container_name: omnicast_caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - path: .env
        required: false
    depends_on:
      - omnicast-engine

  omnicast-engine:
    image: meharab/omnicast_engine:latest
    container_name: omnicast_engine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=8080
      - REDIS_ADDR=${REDIS_ADDR:-127.0.0.1:6379}
    depends_on:
      - omnicast-redis
      - omnicast-coturn

  omnicast-redis:
    image: redis:7-alpine
    container_name: omnicast_redis
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis-data:/data

  omnicast-coturn:
    image: coturn/coturn:latest
    container_name: omnicast_coturn
    restart: unless-stopped
    network_mode: host
    env_file:
      - path: .env
        required: false
    command:
      - turnserver
      - --log-file=stdout
      - --external-ip=${PUBLIC_IP:-127.0.0.1}
      - --listening-port=3478
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET:-omnicast_secret_turn_key}
      - --realm=${TURN_REALM:-testlivekit.lolipoplive.top}

      - --total-quota=100
      - --min-port=49152
      - --max-port=49250
      - -v
      - -n
      - --no-tls
      - --no-dtls

volumes:
  redis-data:
  caddy_data:
  caddy_config:

